### PR TITLE
MainWindow: Use libhandy for rounded corners

### PR DESCRIPTION
**Pull request by JeysonFlores**
I've added rounded corners using `Granite.STYLE_CLASS_ROUNDED` to avoid using `Hdy.Window`. That way the app would look more integrated on eOS 6.
Result:
image

### CODE REVIEW

**Comment by ryonakano** [comment]
Thank you for your contribution! That looks nice, but I wonder why you avoided using Hdy? Making window corners rounded using the elementary stylesheet does not seem to guarantee the window content masked according to [this blog](https://blogs.gnome.org/alexm/2020/04/12/on-windows-and-titlebars/#:~:text=While%20the%20window%20background%20can%20have%20round%20corners%20via%20CSS%20(and%20in%20fact%20that%E2%80%99s%20what%20elementary%20OS%20has%20been%20doing%20with%20the%20.rounded%20style%20class)%2C%20nothing%20prevents%20the%20window%20content%20from%20overlapping%20them.), the app window will not overlap the window content in this case though (because this is not a game app or image viewer). Anyway, this only works well on the elementary stylesheet.

**Comment by JeysonFlores** [comment]
I used `Granite.STYLE_CLASS_ROUNDED` to avoid changing a more substantial part of the original code-base. I know applying that CSS class over the window does not provide all the advantages `Hdy.Window` has but in some cases when you just don't need to overlap anything on the window it just does the trick. The fact that it only works on the elementary stylesheet can also be a drawback however since I discovered this project on the pull request list of appcenter I thought you were doing this specifically for eOS so I didn't consider important the fact that this snippet depends on the elementary stylesheet.

**Comment by ryonakano** [comment]
Yes, this app is meant to be used on elementary OS, but some users likes using customized themes that looks like macOS rather than the default elementary stylesheet. And I thought your method may not work in this case (if these themes don't handle `.rounded` class correctly).
I'm looking forward that this PR is rewritten using Hdy.

**Comment by JeysonFlores** [comment]
Now it uses Hdy.Window to show rounded corners! I had to change Gtk.Headerbar for Hdy.HeaderBar but now it works properly. Also, since now this project uses libhandy, wouldn't be great to add some swipe gestures to go back to homescreen?

**Comment by ryonakano** [comment]
Thanks!

> Also, since now this project uses libhandy, wouldn't be great to add some swipe gestures to go back to homescreen?

Yes, it would be great!

**Review by ryonakano — APPROVED** [review]

**Review by ryonakano — APPROVED** [review]

**Pull request merged**
