### PR TITLE
Add icons

### LINKED ISSUE #3: Add an app icon
Hi @hanaral, sorry for mentioning you but I'd like to ask you a favor.

You made the app icon for [Louper](https://github.com/ryonakano/louper) before and I really like it. And now I've started developing my fourth app here. Would you mind creating an app icon for this app too?

### PR DESCRIPTION
**Pull request by hanaral**
Fixes #3

@ryonakano Here is the 48px icon, I'm not sure if I can do the others that soon - so you might want to ensure that the placeholder 24px and 64px are trying to be loaded

### CODE REVIEW

**Comment by hanaral** [comment]
@ryonakano I've removed the 24px folder and added a 16px one in its place (I think that having 16px is more important)
I've also improved the 48px one

**Comment by ryonakano** [comment]
Thanks for your commits!

According to [the submission requirements](https://github.com/elementary/houston/wiki/Before-You-Publish),

- [ ] 32px
- [x] 48px
- [ ] 64px
- [ ] 128px

are required at least. Would you create these sizes too?

**Comment by hanaral** [comment]
If I have time - it should be straightforward after making the 32px version since I can x2 for 64 and x2 again for 128

**Comment by hanaral** [comment]
@ryonakano 32 and 64 done, you _should_ be able to submit without 128px since 64 scales well

**Comment by ryonakano** [comment]
Indeed, it looks scaling well on my local too. Let's merge your branch and submit the app now!

But I may ask you again if reviewers say "prepare 128px icon because *it's written in the documentation*™, or you can't submit" :sweat_smile:

Thank you very much for your precious time and hard work! I really appreciate it.

**Comment by hanaral** [comment]
@ryonakano 
I've done the 128px icon in case

**Comment by ryonakano** [comment]
OMG, sorry for jumping to conclusions… I'll create a new PR from your branch again

**Pull request merged**
